# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

workspace 'Examples'

target 'InstallMultipleTestSpecs' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for InstallMultipleTestSpecs
  pod 'TestLib', :path => 'TestLib', :testspecs => %w[UnitTests1 UnitTests2]

end
