require_relative '../defaults.rb'

if (repo = ENV['COCOAPODS_SPEC_REPO'])
    source "#{repo}"
end

platform :ios, DEFAULT_IOS_DEPLOYMENT_TARGET

workspace 'Examples'

target 'InstallMultipleTestSpecs' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for InstallMultipleTestSpecs
  pod 'TestLib', :path => 'TestLib', :testspecs => %w[UnitTests1 UnitTests2 UnitTests5]
  pod 'HostedTestLib', :path => 'HostedTestLib', :testspecs => %w[UnitTests3 UnitTests4]
  pod 'ByConfig', path: 'ByConfig', appspecs: %w[App]
end
