platform :osx, '10.14'

pod 'DepPod', :path => 'DepPod'
pod 'HeaderMappingsDirPod', :path => 'HeaderMappingsDirPod'

target 'SampleApp' do

end

target 'OtherSampleApp' do
  use_frameworks!(true)
end
