require_relative '../defaults.rb'

project 'VendoredXCFrameworkExample.xcodeproj'

workspace 'Examples'

target 'VendoredXCFrameworkExample' do
  platform :ios, DEFAULT_IOS_DEPLOYMENT_TARGET
  use_frameworks!

  # XCFramework with Xcode 11 style inclusion of debug symbols
  # To rebuild the xcframework:
  #   cd BananaLib
  #   ./build.sh
  pod 'BananaLib', path: './BananaLib'

  # XCFramework with Xcode 12 style inclusion of debug symbols
  # To rebuild the xcframework:
  #   cd CoconutLib
  #   ./build.sh
  pod 'CoconutLib', path: './CoconutLib'
end
