workspace 'Examples.xcworkspace'
project 'TestInclusions.xcodeproj'
platform :ios, '6.0'

abstract_target 'TestInclusionsPods' do
    pod 'SwrveConversationSDK', '~> 4.11.4'

    target 'TestInclusions'
    target 'TestInclusionsTests'
end
