# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

target "SampleApp" do
  pod 'AFNetworking'

  pod 'ObjectiveSugar'
end

target "SampleApp copy" do
  pod 'AFNetworking'

  pod 'ObjectiveSugar'
end

