require_relative '../defaults.rb'

if (repo = ENV['COCOAPODS_SPEC_REPO'])
    source "#{repo}"
end

workspace 'Examples.xcworkspace'
project 'iOS Example.xcodeproj'

target 'iOS Example' do
  platform :ios, DEFAULT_IOS_DEPLOYMENT_TARGET
  use_frameworks!
  pod 'Alamofire', '5.9.1'
end

