platform :osx

generate_bridge_support!

dependency 'ASIHTTPRequest'
dependency 'SBJson'

# Enable garbage collection support, which MacRuby requires.
post_install do |installer|
  installer.project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['GCC_ENABLE_OBJC_GC'] = 'supported'
    end
  end
end
