platform :osx

generate_bridge_support!

dependency 'ASIHTTPRequest'
dependency 'SBJson'

target :debug do
  dependency 'CocoaLumberjack'
end

target :test, :exclusive => true do
  dependency 'Kiwi'
end
