platform :ios, '8.0'
use_frameworks!

target 'Resource Bundle Example' do
  pod 'ResourceExample', :path =>  'Example Pods'
  pod 'ResourcesExample', :path =>  'Example Pods'
  pod 'ResourceAssetsExample', :path =>  'Example Pods'
end

