platform :ios, '6.0'

pod 'AFNetworking', :git => 'https://github.com/AFNetworking/AFNetworking.git'
pod 'SEGModules', :git => 'https://github.com/segiddins/SEGModules.git'
pod 'RKValueTransformers', :git => 'https://github.com/RestKit/RKValueTransformers'
