if (repo = ENV['COCOAPODS_SPEC_REPO'])
    source "#{repo}"
end

### Implicit target definition :-/
project "AFNetworking Mac Example.xcodeproj"
####

workspace 'Examples.xcworkspace'

target "AFNetworking Example" do
  platform :osx, '10.8'
  project "AFNetworking Mac Example.xcodeproj"
  pod "AFNetworking", "1.3.3"
end

target "AFNetworking iOS Example" do
  platform :ios, '8.0'
  project "AFNetworking iOS Example.xcodeproj"
  pod "AFNetworking", "1.3.3"
end
