if (repo = ENV['COCOAPODS_SPEC_REPO'])
    source "#{repo}"
end

workspace 'Examples.xcworkspace'
project 'iOS Example.xcodeproj'

target 'iOS Example' do
  platform :ios, '9.0'
  use_frameworks!
  pod 'AppCenter', '4.2.0'
end

