Pod::File.new do |f|
  f.platform = :ios
  f.dependency 'SSZipArchive',      '>= 1'
  f.dependency 'ASIHTTPRequest',    '~> 1.8.0'
  f.dependency 'Reachability'                  # part of ASIHTTPRequest
  f.dependency 'ASIWebPageRequest', '< 1.8.2'  # part of ASIHTTPRequest
end
