platform :ios, '6.0'
pod 'Reachability', '3.1.0' # will be inherited by both concrete children

target 'SampleApp' do
  target :SampleAppTests do
    inherit! :search_paths
    pod 'JSONKit'
  end
end

target 'SampleApp_2' do
  pod 'JSONKit'
end
