use_frameworks!

target 'SampleApp' do
  pod 'SamplePodWithResources', :path => 'SamplePodWithResources'
end

target 'SampleAppTests' do
  pod 'SamplePodWithResources', :path => 'SamplePodWithResources'
end
