
dependency 'SSZipArchive', '>= 1'

dependency 'ASIHTTPRequest', '1.8'
#dependency 'ASIWebPageRequest', '= 1.8'

# is part of ASIHTTPRequest 1.8 and 1.8.1
dependency 'Reachability' #, '>= 2.0'

# is part of ASIHTTPRequest
#dependency 'ASIWebPageRequest', '>= 1.8'
#dependency 'ASIWebPageRequest', '= 1.8'

# this should fail the ASIHTTPRequest 1.8.1 hard requirement
#dependency 'ASIWebPageRequest', '1.8.0'

# we have a hard requirement here so:
# * the Reachability dependency should be taken from this version
# * the ASIWebPageRequest dependency requirement matches this one so should work
#dependency 'ASIHTTPRequest', '1.8.1'
#dependency 'ASIHTTPRequest', '>= 1.8'

