require_relative '../defaults.rb'

workspace 'Examples.xcworkspace'
project 'OnDemandResourcesDemo.xcodeproj'

target 'OnDemandResourcesDemo' do
  platform :ios, DEFAULT_IOS_DEPLOYMENT_TARGET
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
    pod 'TestLibrary', :path  => './TestLibrary', :appspecs => ['App1', 'App2'], :testspecs => ['Tests']

  # Pods for OnDemandResourcesDemo

end
