workspace 'Examples.xcworkspace'

use_modular_headers!

abstract_target 'Abstract Target' do
  pod 'ObjCPod', path: 'ObjCPod', :testspecs => %w[Tests]
  pod 'SwiftPod', path: 'SwiftPod', :testspecs => %w[Tests]
  pod 'MixedPod', path: 'MixedPod', :testspecs => %w[Tests]
  pod 'CustomModuleMapPod', path: 'CustomModuleMapPod', :testspecs => %w[Tests]

  %w[iOS macOS].each do |platform|
    abstract_target "#{platform} Pods" do
      project "#{platform} Modules.xcodeproj"

      case platform
      when 'iOS' then self.platform :ios, '10.0'
      when 'macOS' then self.platform :macos, '10.10'
      end

      target 'Static' do
          use_frameworks!(false)
      end
      target 'Dynamic' do
          use_frameworks!(true)
      end
    end
  end
end

ENV['COCOAPODS_DISABLE_STATS'] = 'true'
