require_relative '../defaults.rb'

if (repo = ENV['COCOAPODS_SPEC_REPO'])
    source "#{repo}"
end

use_frameworks!

workspace 'Examples.xcworkspace'
project 'watchOSsample.xcodeproj'

target 'watchOSsample' do
  platform :ios, DEFAULT_IOS_DEPLOYMENT_TARGET
  pod 'Alamofire', '5.9.1'
end

target 'watchOSsample WatchKit Extension' do
  platform :watchos, DEFAULT_WATCHOS_DEPLOYMENT_TARGET
  pod 'Alamofire', '5.9.1'
end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
          config.build_settings['WATCHOS_DEPLOYMENT_TARGET'] = DEFAULT_WATCHOS_DEPLOYMENT_TARGET
      end
    end
  end
end
