require_relative '../defaults.rb'

if (repo = ENV['COCOAPODS_SPEC_REPO'])
    source "#{repo}"
end

use_frameworks!

workspace 'Examples.xcworkspace'
project 'watchOSsample.xcodeproj'

target 'watchOSsample' do
  platform :watchos, DEFAULT_WATCHOS_DEPLOYMENT_TARGET
  pod 'Alamofire', '5.9.1'
end

target 'watchOSsample WatchKit Extension' do
  platform :watchos, DEFAULT_WATCHOS_DEPLOYMENT_TARGET
  pod 'Alamofire', '5.9.1'
end
