if (repo = ENV['COCOAPODS_SPEC_REPO'])
    source "#{repo}"
end

use_frameworks!

workspace 'Examples.xcworkspace'
project 'watchOSsample.xcodeproj'

target 'watchOSsample' do
  pod 'Alamofire', :path => '../Alamofire Example/Alamofire'
end

target 'watchOSsample WatchKit Extension' do
  platform :watchos, '4.0'
  pod 'Alamofire', :path => '../Alamofire Example/Alamofire'
end
