# SampleApp is the first target i.e. default
platform :ios, '6.0'
pod "Reachability", "3.1.0"

target :test, :exclusive => true do
  link_with 'SampleAppTests'
  pod 'JSONKit'
end

target 'SampleApp_2' do
  pod 'JSONKit'
end
