# As this file is loaded pretty early, we can use this opportunity to clean
# the integrated project, if it exists, and setup an unintegrated version.
require 'fileutils'
integrated   = File.expand_path('../RelativePathProject/RelativePathProject.xcodeproj', __FILE__)
unintegrated = File.expand_path('../RelativePathProject/RelativePathProject.xcodeproj.unintegrated', __FILE__)
FileUtils.rm_rf(integrated)
FileUtils.cp_r(unintegrated, integrated)


platform :ios

xcodeproj "RelativePathProject/RelativePathProject.xcodeproj"

pod "AFNetworking"
