platform :ios

dependency 'FormatterKit'

dependency do |s|
  s.name     = 'AFNetworking'
  s.version  = '0.7.0'
  s.summary  = 'A delightful iOS networking library with NSOperations and block-based callbacks'
  s.homepage = 'https://github.com/gowalla/AFNetworking'
  s.author   = { 'Gowalla' => 'live@gowalla.com' }
  s.source   = { :git => 'https://github.com/gowalla/AFNetworking.git', :tag => '0.7.0' }

  if config.ios?
    s.source_files = 'AFNetworking' # everything
  else
    s.source_files = %w{
      AFNetworking/AFHTTPRequestOperation.h
      AFNetworking/AFJSONRequestOperation.h
      AFNetworking/NSData+AFNetworking.h
      AFNetworking/NSMutableURLRequest+AFNetworking.h
      AFNetworking/NSString+AFNetworking.h
    }
  end

  s.clean_paths = ['iOS Example', 'Mac Example', 'AFNetworking.xcworkspace']

  s.library = 'z'
  s.dependency 'JSONKit'
end
