#!/usr/bin/ruby --disable-gems

require "pathname"

file_path = Pathname.new(__FILE__).realpath
gems_setup = File.expand_path("../../vendor/gems/setup.rb", file_path)

require gems_setup

$LOAD_PATH.unshift(File.expand_path("../../rubylib", file_path))


if RUBY_VERSION > '2.0.0' && Encoding.default_external != Encoding::UTF_8
  puts "\e[33mWARNING: CocoaPods requires your terminal to be using UTF-8 encoding."
  if ENV['TRAVIS']
    puts <<-DOC
Consider adding the following settings to .travis.yml

before_script:
  - export LANG=en_US.UTF-8\e[0m\n
    DOC
  else
    puts <<-DOC
See https://github.com/CocoaPods/guides.cocoapods.org/issues/26 for
possible solutions.\e[0m\n
    DOC
  end
end

STDOUT.sync = true if ENV['CP_STDOUT_SYNC'] == 'TRUE'

require 'cocoapods'
Pod::Command.run(ARGV)
