if (repo = ENV['COCOAPODS_SPEC_REPO'])
    source "#{repo}"
end

use_frameworks!

workspace 'Examples.xcworkspace'
project 'HeaderMappingsDir Example.xcodeproj'

target 'App' do
  platform :osx, '10.9'
  pod 'HeaderMappingsDirPod', :path => 'HeaderMappingsDirPod'
end

target 'CatalystApp' do
  platform :ios, '13.0'
  pod 'HeaderMappingsDirPod', :path => 'HeaderMappingsDirPod'
end
