require_relative '../defaults.rb'

if (repo = ENV['COCOAPODS_SPEC_REPO'])
    source "#{repo}"
end

use_frameworks!

workspace 'Examples.xcworkspace'
project 'HeaderMappingsDir Example.xcodeproj'

target 'App' do
  platform :osx, DEFAULT_MACOS_DEPLOYMENT_TARGET
  pod 'HeaderMappingsDirPod', :path => 'HeaderMappingsDirPod'
end

target 'CatalystApp' do
  platform :ios, DEFAULT_IOS_DEPLOYMENT_TARGET
  pod 'HeaderMappingsDirPod', :path => 'HeaderMappingsDirPod'
end
